### ISSUE TITLE
Fixing timeouts

### ISSUE THREAD

**Issue by tillkruss** [codecov/codecov-action#37]
We're seeing timeouts when running out test suite.

How can we prevent that? Is there maybe rate limiting going on?

<img width="723" alt="Screen Shot 2019-11-29 at 12 33 54 PM" src="https://user-images.githubusercontent.com/665029/69889234-b0e5ad00-12a4-11ea-9d2d-59e4f94bcf62.png">

<img width="826" alt="Screen Shot 2019-11-29 at 12 34 22 PM" src="https://user-images.githubusercontent.com/665029/69889281-dbd00100-12a4-11ea-977a-898bc1a91376.png">

**Comment by ibrahim0814** [comment]
Hi @tillkruss, thank you for bringing this up! We're investigating this internally - it seems to be a server-side issue which is impacting users with a large number of report uploads. Will post an update here when we've diagnosed and fixed this fully

**Comment by tillkruss** [comment]
Great.

We have a single workflow, but 16 runs with different configurations.

<img width="975" alt="Screen Shot 2019-12-02 at 12 33 48 PM" src="https://user-images.githubusercontent.com/665029/69993231-3dd87280-1500-11ea-8a2a-b0b947d19b2b.png">

**Comment by JCMais** [comment]
Same issue here, stacktrace:
```
/home/runner/work/_actions/codecov/codecov-action/v1/dist/index.js:292
      throw error;
      ^

Error: connect ETIMEDOUT 35.199.43.247:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1054:14) {
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '35.199.43.247',
  port: 443
}
```

**Comment by postlund** [comment]
I have the exact same problem in pyatv. Really annoying to have to restart all the time.

**Comment by ttimbers** [comment]
Same issue happening to me.

**Comment by JekaMas** [comment]
And for us...
```
Run codecov/codecov-action@v1
/home/runner/work/_actions/codecov/codecov-action/v1/dist/index.js:292
      throw error;
      ^

Error: connect ETIMEDOUT 35.199.43.247:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1129:14) {
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '35.199.43.247',
  port: 443
}
```

**Comment by ibrahim0814** [comment]
Hi all,

We identified a bug within Minio that seems to be causing these timeouts to occur. Our engineers have already merged a PR to fix this, and in the process, some other issues have sprung up which we've also PRed into the Minio repo. We're working hard to get those other fixes merged and a new version of Minio deployed with our infra as soon as possible, so I apologize for the delay in addressing this. 

Ib

**Comment by dgattey** [comment]
Same issue just hit us today - any progress?

**Comment by tillkruss** [comment]
@ibrahim0814: Any update on the deployment?

**Comment by rivy** [comment]
We're hitting this issue intermittently for [`coreutils`](https://github.com/uutils/coreutils) MacOS test uploads (see <https://github.com/rivy/rs.coreutils/runs/725847137?check_suite_focus=true>).

Was the fix mentioned here merged?

**Comment by mmoayyed** [comment]
As another data point, also seeing intermittent failures:

![image](https://user-images.githubusercontent.com/1205228/83791449-116c0180-a6af-11ea-8680-887b9aaf66a3.png)

**Comment by postlund** [comment]
Has the problem gotten worse lately? I'm barely able to merge things because of problems with codecov.

**Comment by M-Adoo** [comment]
Almost every pr failed. 😔

**Comment by tillkruss** [comment]
@thomasrockhu: Was the original issue resolved? How are cookies related to the CI timeouts?

**Comment by JekaMas** [comment]
> I'm going to close out this issue, because many of the comments are due to different issues.

However, it doesn't solve the issue. We're still having this issue from time to time.

**Comment by thomasrockhu** [comment]
Fair enough. It is a little bit easier for us to track this on the community boards. @JekaMas @tillkruss has this happened to you recently after the fix? If so, if you can provide commit SHAs or the Codecov output, that would be extremely helpful.

Again, preference is towards the boards, but I understand if this fits better into your workflows.

**Comment by rivy** [comment]
We're still having this issue crop up frequently (though irregularly) for [coreutils](https://github.com/uutils/coreutils) MacOS test uploads (see <https://github.com/rivy/rs.coreutils/runs/725847137?check_suite_focus=true> and <https://github.com/uutils/coreutils/runs/769224500?check_suite_focus=true>).

Where would you prefer to discuss it?

**Comment by adithyabsk** [comment]
I'm still running into this issue as well: https://pipelines.actions.githubusercontent.com/WMazgylCfCu4ko1Ltxzy3Jxgf9FHIkKNNu6qjxJ2D1DT9WzVqF/_apis/pipelines/1/runs/118/signedlogcontent/28?urlExpires=2020-06-22T05%3A07%3A00.2620951Z&urlSigningMethod=HMACV1&urlSignature=FQBl0NtgxYMJRYkVf3%2Br9xEedvqiW7HjTHXsOWcRmVI%3D

**Comment by The-Compiler** [comment]
FWIW I'm also seeing this on GitHub Actions: https://github.com/qutebrowser/qutebrowser/runs/834775872?check_suite_focus=true#step:10:1

**Comment by mmoayyed** [comment]
Switch to 1.0.10

**Comment by The-Compiler** [comment]
@mmoayyed Hmm, shouldn't `v1` always point at the newest v1 (i.e. v1.0.10) rather than v1.0.0?

**Comment by rivy** [comment]
This seems to now be fixed in my GHA builds (no config changes; still using `codecov/codecov-action@v1`).

**Comment by thomasrockhu** [comment]
@The-Compiler, it should have, but `1.0.10` was released on the same day. It could have just been an issue with timing, but hopefully this should be resolved for you. I'm going to close out this issue now, but if it crops up, please feel free to make a support post on our [community boards](community.codecov.io).

**Comment by adamtheturtle** [comment]
I am still seeing this issue regularly - see [this build from a few hours ago](https://github.com/VWS-Python/vws-python-mock/actions/runs/212647896).

**Comment by adamtheturtle** [comment]
FYI @thomasrockhu your link to the community boards should be to https://community.codecov.io but it takes me to https://github.com/codecov/codecov-action/issues/community.codecov.io which is a 404.

**Comment by thomasrockhu** [comment]
Whoops! thanks @adamtheturtle

**Comment by adamtheturtle** [comment]
<img width="1290" alt="Screenshot 2020-08-18 at 00 03 42" src="https://user-images.githubusercontent.com/797801/90452547-574d3900-e0e6-11ea-9c45-8bbb59f256b3.png">

This just happened again, on 1.0.12, after 11 minutes.
