### ISSUE TITLE
Error: Codecov: Failed to properly upload...

### ISSUE THREAD

**Issue by mdesalvo** [codecov/codecov-action#595]
Hi,
since today I'm starting to get intermittent failures during the execution of the CodeCov v2.1.0 action at the report upload stage.
Here is the latest log:

```
Run codecov/codecov-action@v2.1.0
==> windows OS detected
https://uploader.codecov.io/latest/windows/codecov.exe.SHA256SUM
==> SHASUM file signed by key id 806bb28aed779869
==> Uploader SHASUM verified (868ad3a24cd143022b40a9fc4be07c1d71e5ccc855235787d178c06860e5d886  codecov.exe)
==> Running version latest
==> Running version v0.1.9
D:\a\_actions\codecov\codecov-action\v2.1.0\dist\codecov.exe -n "" -Q github-action-2.1.0 -Z -v
[2021-12-06T20:18:42.496Z] ['verbose'] Start of uploader: 1638821922496...
[2021-12-06T20:18:42.501Z] ['info'] 
     _____          _
    / ____|        | |
   | |     ___   __| | ___  ___ _____   __
   | |    / _ \ / _` |/ _ \/ __/ _ \ \ / /
   | |___| (_) | (_| |  __/ (_| (_) \ V /
    \_____\___/ \__,_|\___|\___\___/ \_/

  Codecov report uploader 0.1.13
[2021-12-06T20:18:42.536Z] ['info'] => Project root located at: D:/a/RDFSharp/RDFSharp
[2021-12-06T20:18:42.537Z] ['info'] -> No token specified or token is empty
[2021-12-06T20:18:42.537Z] ['verbose'] Start of network processing...
[2021-12-06T20:18:42.537Z] ['verbose'] Searching for files in D:/a/RDFSharp/RDFSharp
[2021-12-06T20:18:42.571Z] ['info'] Searching for coverage files...
[2021-12-06T20:18:42.602Z] ['verbose'] Preparing to clean the following coverage paths: RDFSharp.Test/TestResults/d43850e8-cfc9-42be-a2e3-2539cf41ce63/coverage.cobertura.xml
[2021-12-06T20:18:42.607Z] ['info'] => Found 1 possible coverage files:
  RDFSharp.Test/TestResults/d43850e8-cfc9-42be-a2e3-2539cf41ce63/coverage.cobertura.xml
[2021-12-06T20:18:42.607Z] ['verbose'] End of network processing
[2021-12-06T20:18:42.607Z] ['info'] Processing D:/a/RDFSharp/RDFSharp/RDFSharp.Test/TestResults/d43850e8-cfc9-42be-a2e3-2539cf41ce63/coverage.cobertura.xml...
[2021-12-06T20:18:42.699Z] ['info'] Detected GitHub Actions as the CI provider.
[2021-12-06T20:18:42.700Z] ['verbose'] -> Using the following env variables:
[2021-12-06T20:18:42.700Z] ['verbose']      GITHUB_ACTION: __codecov_codecov-action
[2021-12-06T20:18:42.700Z] ['verbose']      GITHUB_HEAD_REF: 
[2021-12-06T20:18:42.700Z] ['verbose']      GITHUB_REF: refs/heads/master
[2021-12-06T20:18:42.700Z] ['verbose']      GITHUB_REPOSITORY: mdesalvo/RDFSharp
[2021-12-06T20:18:42.700Z] ['verbose']      GITHUB_RUN_ID: 1546414823
[2021-12-06T20:18:42.700Z] ['verbose']      GITHUB_SERVER_URL: https://github.com
[2021-12-06T20:18:42.700Z] ['verbose']      GITHUB_SHA: a1a32536b4ccd5db0efae8cfbb47589ac32a9855
[2021-12-06T20:18:42.700Z] ['verbose']      GITHUB_WORKFLOW: windows
[2021-12-06T20:18:42.700Z] ['verbose'] Using the following upload parameters:
[2021-12-06T20:18:42.700Z] ['verbose'] branch
[2021-12-06T20:18:42.700Z] ['verbose'] build
[2021-12-06T20:18:42.700Z] ['verbose'] buildURL
[2021-12-06T20:18:42.700Z] ['verbose'] commit
[2021-12-06T20:18:42.700Z] ['verbose'] job
[2021-12-06T20:18:42.700Z] ['verbose'] pr
[2021-12-06T20:18:42.700Z] ['verbose'] service
[2021-12-06T20:18:42.700Z] ['verbose'] slug
[2021-12-06T20:18:42.700Z] ['verbose'] name
[2021-12-06T20:18:42.700Z] ['verbose'] tag
[2021-12-06T20:18:42.700Z] ['verbose'] flags
[2021-12-06T20:18:42.700Z] ['verbose'] parent
[2021-12-06T20:18:42.701Z] ['info'] Pinging Codecov: https://codecov.io/upload/v4?package=github-action-2.1.0-uploader-0.1.13&token=*******&branch=master&build=1546414823&build_url=https%3A%2F%2Fgithub.com%2Fmdesalvo%2FRDFSharp%2Factions%2Fruns%2F1546414823&commit=a1a32536b4ccd5db0efae8cfbb47589ac32a9855&job=windows&pr=&service=github-actions&slug=mdesalvo%2FRDFSharp&name=&tag=&flags=&parent=
[2021-12-06T20:18:42.701Z] ['verbose'] Passed token was 0 characters long
[2021-12-06T20:18:42.701Z] ['verbose'] https://codecov.io/upload/v4?package=github-action-2.1.0-uploader-0.1.13&branch=master&build=1546414823&build_url=https%3A%2F%2Fgithub.com%2Fmdesalvo%2FRDFSharp%2Factions%2Fruns%2F1546414823&commit=a1a32536b4ccd5db0efae8cfbb47589ac32a9855&job=windows&pr=&service=github-actions&slug=mdesalvo%2FRDFSharp&name=&tag=&flags=&parent=
        Content-Type: 'text/plain'
        Content-Encoding: 'gzip'
        X-Reduced-Redundancy: 'false'
[2021-12-06T20:18:43.007Z] ['error'] There was an error running the uploader: Error uploading to https://codecov.io: Error: There was an error fetching the storage URL during POST: 404 - Not Found - {'detail': ErrorDetail(string='Unable to locate build via Github Actions API. Please upload with the Codecov repository upload token to resolve issue.', code='not_found')}
[2021-12-06T20:18:43.008Z] ['verbose'] The error stack is: Error: Error uploading to https://codecov.io: Error: There was an error fetching the storage URL during POST: 404 - Not Found - {'detail': ErrorDetail(string='Unable to locate build via Github Actions API. Please upload with the Codecov repository upload token to resolve issue.', code='not_found')}
    at main (C:\snapshot\project\dist\src\index.js)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2021-12-06T20:18:43.008Z] ['verbose'] End of uploader: 512 milliseconds
Error: Codecov: Failed to properly upload: The process 'D:\a\_actions\codecov\codecov-action\v2.1.0\dist\codecov.exe' failed with exit code 4294967295
```

Can you please help me?
Regards,
Marco

**Comment by victorlin** [comment]
Also seeing this. It was just working about an hour ago:

- [`2021-12-06T19:49` success](https://github.com/nextstrain/augur/runs/4435309394?check_suite_focus=true#step:11:31)
- [`2021-12-06T20:11` failure](https://github.com/nextstrain/augur/runs/4435544484?check_suite_focus=true#step:11:31)

**Comment by mdesalvo** [comment]
It seems resolved now, yesterday all runs succeeded. I'll still monitor today and close the request in case ok.

**Comment by rowanseymour** [comment]
We still see this on probably 25% of codecov uploads.

For example from earlier this morning

```
Codecov report uploader 0.2.5
[2022-08-22T15:08:04.976Z] ['info'] => Project root located at: /home/runner/work/rapidpro/rapidpro
[2022-08-22T15:08:04.980Z] ['info'] -> No token specified or token is empty
[2022-08-22T15:08:04.995Z] ['info'] Searching for coverage files...
[2022-08-22T15:08:05.721Z] ['info'] Warning: Some files located via search were excluded from upload.
[2022-08-22T15:08:05.721Z] ['info'] If Codecov did not locate your files, please review https://docs.codecov.com/docs/supported-report-formats
[2022-08-22T15:08:05.722Z] ['info'] => Found 2 possible coverage files:
  coverage.xml
  .venv/bin/coverage-3.9
[2022-08-22T15:08:05.722Z] ['info'] Processing /home/runner/work/rapidpro/rapidpro/coverage.xml...
[2022-08-22T15:08:05.726Z] ['info'] Processing /home/runner/work/rapidpro/rapidpro/.venv/bin/coverage-3.9...
[2022-08-22T15:08:05.743Z] ['info'] Detected GitHub Actions as the CI provider.
[2022-08-22T15:08:05.745Z] ['info'] Pinging Codecov: https://codecov.io/upload/v4?package=github-action-2.1.0-uploader-0.2.5&token=*******&branch=api_anon_display&build=2904846285&build_url=https%3A%2F%2Fgithub.com%2Fnyaruka%2Frapidpro%2Factions%2Fruns%2F2904846285&commit=a7a7a2a8414d76be7fd5d1d4fbaa46cbd8c2a646&job=CI&pr=[39](https://github.com/nyaruka/rapidpro/runs/7954553179?check_suite_focus=true#step:17:40)58&service=github-actions&slug=nyaruka%2Frapidpro&name=&tag=&flags=&parent=
[2022-08-22T15:08:06.066Z] ['error'] There was an error running the uploader: Error uploading to https://codecov.io: Error: There was an error fetching the storage URL during POST: [40](https://github.com/nyaruka/rapidpro/runs/7954553179?check_suite_focus=true#step:17:41)4 - {'detail': ErrorDetail(string='Unable to locate build via Github Actions API. Please upload with the Codecov repository upload token to resolve issue.', code='not_found')}`
```
